sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: nTBps9U4fxLjcGP7nZh8OOBIx8J7YQW/Dn3iqEgx8hloqT5kWvWr56aOEUZCDT/QdTAsp728XBfwEitV+zJMOTEak71n9U+ptOcKPoCOp+3GhJdi4T5qVdN/wIhcIIMIJ0Z/90PDx9xwEPELxU+9Q3/rUdYar0FERZR0gd8g2fjd/Sl65kULhsh3j2iandfIzbqpeQFCdwQEVHurJ909lsRUcZS3SuKuWo7LYZtlz6REr9oi7FiHjSc4qxe12lzjm6DjpLp28sUJtawgHkhkrx/Dd0cFYBdAisA/HuwapQl+pGa577g2ooB7M00AwMrcmGbrIswUOdw0cE9ICTXdgT0geLdtU0H3YRHvlVug7oJzZ7zOXV/c3yTZkTm0drTlF/kDBUyG1VaE+LNalLqx/rf68u5r7C7xGTTtkx1/D8LdBRO/uhT85OeV2fx6cJIu28mxfDHAfMLN+NnZ/edxPdg483WSRiDtn6az1Arjx9ndDP0yR2rV2YHWdDuhMa7Z1JLwxglaV0YRG5Xtgw0lGIzjxGekWGAp2QrKWjvMR9voi405piVuctIBrmMTT3utPRoZqJKEIsXlu4buuCg9Mm8BTv20N1u3oqoBSpj7uHn4IFRwd31E65Elv20/iXpQWWieR2wG593sQUPe7yBQZSYh/zt5rm3U4m8+ptNa4aQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Gutenberg-Webster-s-Unabridged-Dictionary-Section-I-J-K-and-L_664
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy